apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: hello-port-8080
  loadBalancerIP: 104.197.233.82
  selector:
    app: hello
